server:
  port: ${PORT:8982}
logging:
  file: flow.log

  #level:
    #com:
      #checkmarx:
        #flow: TRACE

cx-flow:
  bug-tracker: None
  bug-tracker-impl:
    # - Azure
    # - Csv
    # - CxXml
    # - GitHub
    # - GitLab
    # - Rally
    # - Json
    # - Sarif
    # GITLABMERGE
    # - SonarQube
    # - JIRA
  enabled-vulnerability-scanners:
  #- sast
  - sca
  branches:
  - master
  - dev\w+
  - release-\w+
  filter-severity:
  #- High
  thresholds:
    HIGH: 5
    MEDIUM: 1
    LOW: 3 
  filter-category:
  #- SQL_Injection
  #- Stored_XSS
  #- Reflected_XSS_All_Clients
  filter-cwe:
  filter-status:
  # - Urgent
  # - Confirmed
  # - To Verify
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  #wiki-url: https://custodela.atlassian.net/wiki/spaces/AS/pages/79462432/Remediation+Guidance
  codebash-url: https://checkmarx-demo.codebashing.com/courses/
  #comment-script: C:\Checkmarx\git\cx-flow-834\src\main\resources\samples\ScanComment.groovy
  scan-resubmit: true

sonarqube:
  file-path: C:\Checkmarx\History\SonarQube\cxSonarQube.json
    
codebashing:
  codebashing-api-url: https://api.devcodebashing.com/lessons
  tenant-base-url: https://checkmarx.codebashing.com
  api-secret: DOwEHVb1aF1YpYRhk41HL4oeh54B149Q5SPH2b3E  
  
checkmarx:
  version: 9.4
  username: admin@cx
  password: Cx123456!
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  #base-url: http://10.32.8.7
  base-url: http://10.32.0.135
  team: /CxServer
  #username: cxflowDhaval
  #password: gk7(-W&Y42
  #client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  #base-url: https://cxapactrial.checkmarx.net
  #team: /CxServer/SP/ANZ/CBA-GH-POC
  url: ${checkmarx.base-url}/cxrestapi
  #scan-preset: Checkmarx Default
  incremental: false
  #WSDL Config
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
  portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
  sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl
  scan-queuing: false
  scan-timeout: 130

sca:
  appUrl: https://sca.checkmarx.net
  apiUrl: https://api-sca.checkmarx.net
  accessControlUrl: https://platform.checkmarx.net
  tenant: Plugins
  username: hussains
  password: Cx123456!
  team: "/CxServer"
  scan-timeout: 120
  #filter-severity:
    #- High
    
azure:
  webhook-token: cxflow:12345
  token: kt4yohhrjnzcq6gkonkgwjqkdvvuyixargqgpajkp4rg75vqe2iq
  url: https://dev.azure.com/
  issue-type: issue
  api-version: 5.0
  false-positive-label: false-positive
  #block-merge: true
  closed-status: Done
  open-status: "To Do"

bitbucket:
  webhook-token: 12345
  token: ###<bitbucketuser>###:###<bitbuckettoken>###
  url: https://api.bitbucket.org
  api-path: /2.0

github:
  webhook-token: 12345
  #token: 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
  token: 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
  url: https://github.com
  api-url: https://api.github.com/repos/
  false-positive-label: false-positive
  #block-merge: true
  #error-merge: true
  #cx-summary: true

gitlab:
  webhook-token: 12345
  token: glpat-szs9zfc28uMr1uPpAcvJ
  url: https://gitlab.com
  api-url: https://gitlab.com/api/v4/
  false-positive-label: false-positive
  block-merge: true
  error-merge: true

jira:
  url: https://cxflowuser.atlassian.net/
  username: hussain.saifuddin@checkmarx.com
  token: Txda0ZeWxh6dTiv0zFTED209
  project: HFIRST
  issue-type: Application Security Bug
  priorities:
     Critical: Highest
     High: High
     Medium: Medium
     Low: Low
     Informational: Lowest
  open-transition: Backlog
  close-transition: Done
  open-status:
    - Backlog
    - Selected for Development
    - In Progress
  closed-status:
    - Done
  fields:
     - type: result
       name: application
       jira-field-name: Application
       jira-field-type: label
     - type: result
       name: cve
       jira-field-name: CVEs
       jira-field-type: label
     - type: result
       name: cwe
       jira-field-name: CWEs
       jira-field-type: label
     - type: result
       name: category
       jira-field-name: Category
       jira-field-type: label
     - type: result
       name: loc
       jira-field-name: LOC
       jira-field-type: label
       jira-default-value: XXXXX
