# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This is a basic workflow to help you get started with Using Checkmarx CxFlow Action

name: CxFlow

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '24 23 * * 4'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel - this job is specifically configured to use the Checkmarx CxFlow Action
permissions:
  contents: read

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on - Ubuntu is required as Docker is leveraged for the action
    permissions:
      contents: read # for actions/checkout to fetch code
      issues: write # for checkmarx-ts/checkmarx-cxflow-github-action to write feedback to github issues
      pull-requests: write # for checkmarx-ts/checkmarx-cxflow-github-action to write feedback to PR
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest

    # Steps require - checkout code, run CxFlow Action, Upload SARIF report (optional)
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    # Runs the Checkmarx Scan leveraging the latest version of CxFlow - REFER to Action README for list of inputs
    - name: Checkmarx CxFlow Action
      uses: "nidhi0512/checkmarx-cxflow-github-action@ba5cec16b01e4a3cdea681a4fbada6ccbaa2fe25"
      with:
        project: Test1
        team: /CxServer/NidhiJaiswal
        checkmarx_url: http://e9d6-31-168-164-190.ngrok.io
        checkmarx_username: admin@cx
        checkmarx_password: Cx12345678!
        checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C
        checkmarx_preset: Checkmarx Default
        checkmarx_incremental: false
        break_build: false
        bug_tracker: JIRA
        bug_tracker_impl: JIRA
        jira_url: https://nidhikjaiswal.atlassian.net/
        jira_username: jaiswal.nidhi0512@gmail.com
        jira_token: RDm6BfRLY47l0OtJsuQp6FE8
        jira_issue_type: 'Bug'
        jira_open_transition: 'In Progress'
        jira_close_transition: 'Done'
        jira_open_status: 'In Progress, In Review'
        jira_closed_status: 'Done'
        github_token: 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
        scanners: sast
        params: --logging.level.com.checkmarx.flow.custom=debug --logging.level.com.checkmarx.flow.service=debug --logging.level.com.checkmarx.flow.utils=debug --logging.level.com.checkmarx.sdk.service=debug --jira_project= APPSEC --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --repo-name=CxFlowBodgeit --cx-flow.filter-severity --cx-flow.filter-category --checkmarx.disable-clubbing=true --repo-url=${{ github.event.repository.url }}
    # Upload the Report for CodeQL/Security Alerts
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: cx.sarif
