          checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C
    # Select a Checkmarx Project
          project:  ${{ GITHUB.REPOSITORY }}
    # Select an Application Name used by downstream bug tracker systems
          app: ${{ GITHUB.REPOSITORY }}
    # Select a Checkmarx Preset
          preset: 'Checkmarx Express'
    # Break build based on Checkmarx findings?
          break_build: true  # optional
    # Bug tracker for the scan results.
          bug_tracker: ${{ inputs.bugtracker}}
    # Incremental Scans?
          incremental: false # optional, default is true
    # Additional CLI parameters
          params: --branch=${{ inputs.branch }}
                  --repo-name=${{ github.event.repository.name }}
                  --merge-id=${{ github.event.number }}
                  --namespace=${{ github.repository_owner }}
                  --cx-flow.filter-state=${{ steps.myvars.outputs.state }}
                  --cx-flow.filter-severity=${{ steps.myvars.outputs.severity }}
    #              --sca.filter-severity=${{ steps.myvars.outputs.severity }}
    #              --cx-flow.filter-status=${{ steps.myvars.outputs.status }}
    #              --sca.filter-score=9.0
    #             --cx-flow.filter-category=""
    #             --sca.includeSources=true
    #             --sca.enabledZipScan=true
    # GitHub API Token
          github_token: ${{ secrets.GITHUB_TOKEN }}
    # Vulnerability Scanners (sast, sca, ast, cxgo)
          scanners: sast
    # Provide SCA API URL
          sca_api_url: https://api-sca.checkmarx.net 
    # Provide SCA APP URL
          sca_app_url: https://sca.checkmarx.net 
    # Provide SCA Access Control URL
          sca_access_control_url: https://platform.checkmarx.net
    # Provide SCA Tenant
          sca_tenant: SCA_Jurgan_Eitle
    # Provide SCA Username
          sca_username: ${{ secrets.sca_username }}
    # Provide SCA Password
          sca_password: ${{ secrets.sca_password }}
   
